import React, { useState } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../../context/AuthContext';
import { 
  Shield, 
  Lock, 
  Mail, 
  Eye, 
  EyeOff, 
  AlertCircle, 
  BadgeCheck, 
  ArrowRight,
  ChevronRight
} from 'lucide-react';

export default function Login() {
  const { login } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  // Authentication states
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [role, setRole] = useState('investigator'); // default FastAPI role-claim matches
  const [rememberMe, setRememberMe] = useState(false);
  
  // Interface states
  const [showPassword, setShowPassword] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [validationErrors, setValidationErrors] = useState({});

  // Resolve redirection target if redirected by a ProtectedRoute
  const redirectTarget = location.state?.from?.pathname || '/dashboard';

  // Basic frontend input verification
  const validateForm = () => {
    const errors = {};
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

    if (!email) {
      errors.email = 'Badge email address is required';
    } else if (!emailRegex.test(email)) {
      errors.email = 'Invalid investigative email format';
    }

    if (!password) {
      errors.password = 'Authentication credentials are required';
    } else if (password.length < 6) {
      errors.password = 'Credentials must be at least 6 characters';
    }

    setValidationErrors(errors);
    return Object.keys(errors).length === 0;
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setErrorMessage('');
    
    if (!validateForm()) return;

    setIsLoading(true);
    try {
      // Direct integration with our AuthContext wrapper mapping to /auth/login
      // We pass the email/badge reference along with current active system target role
      await login(email, password, { role, rememberMe });
      navigate(redirectTarget, { replace: true });
    } catch (err) {
      // Captures structure generated by our Axios wrapper formatting rules
      setErrorMessage(err.message || 'Verification rejected. Check credentials or authorization level.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex items-center justify-center p-4 font-sans relative overflow-hidden selection:bg-purple-500/30">
      
      {/* Structural ambient backdrop decorations */}
      <div className="absolute top-1/4 left-1/4 w-96 h-96 bg-purple-600/10 rounded-full blur-[128px] pointer-events-none" />
      <div className="absolute bottom-1/4 right-1/4 w-96 h-96 bg-indigo-600/10 rounded-full blur-[128px] pointer-events-none" />
      
      <div className="w-full max-w-md bg-slate-900 border border-slate-800 rounded-2xl shadow-2xl overflow-hidden relative z-10">
        
        {/* Decorative Top Accent Bar */}
        <div className="h-1.5 w-full bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500" />

        <div className="p-8">
          
          {/* Header Block */}
          <div className="flex flex-col items-center text-center mb-8">
            <div className="w-12 h-12 bg-purple-500/10 border border-purple-500/20 rounded-xl flex items-center justify-center text-purple-400 mb-3 shadow-inner">
              <Shield className="w-6 h-6 animate-pulse" />
            </div>
            <h1 className="text-xl font-extrabold tracking-tight text-white flex items-center gap-1.5">
              KSP IntelliCrime AI
            </h1>
            <p className="text-xs text-slate-400 mt-1">
              Secured Federal Intelligence Portal
            </p>
          </div>

          {/* Form Level Error Reports */}
          {errorMessage && (
            <div className="mb-6 p-3.5 bg-red-500/10 border border-red-500/20 rounded-lg text-xs text-red-400 flex items-start gap-2.5">
              <AlertCircle className="w-4 h-4 shrink-0 mt-0.5" />
              <span>{errorMessage}</span>
            </div>
          )}

          {/* Interactive Form Block */}
          <form onSubmit={handleSubmit} className="space-y-5">
            
            {/* System Clearance Role Select */}
            <div>
              <label className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-2">
                Authorization Clearance
              </label>
              <div className="grid grid-cols-3 gap-2">
                {['investigator', 'analyst', 'admin'].map((r) => (
                  <button
                    key={r}
                    type="button"
                    onClick={() => setRole(r)}
                    className={`py-2 px-3 text-xs font-semibold rounded-lg border capitalize transition-all ${
                      role === r
                        ? 'bg-purple-500/10 border-purple-500 text-purple-400'
                        : 'bg-slate-950/40 border-slate-850 text-slate-400 hover:border-slate-800'
                    }`}
                  >
                    {r}
                  </button>
                ))}
              </div>
            </div>

            {/* Email / Badge Identification */}
            <div>
              <label className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider mb-1.5">
                Investigator Email / Badge Identifier
              </label>
              <div className="relative">
                <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-slate-500">
                  <Mail className="w-4 h-4" />
                </span>
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className={`w-full bg-slate-950 border text-sm text-slate-200 rounded-xl pl-10 pr-4 py-2.5 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500/20 transition-all font-mono ${
                    validationErrors.email ? 'border-red-500/50' : 'border-slate-850'
                  }`}
                  placeholder="badge@ksp-intel.gov"
                />
              </div>
              {validationErrors.email && (
                <p className="text-[10px] text-red-400 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {validationErrors.email}
                </p>
              )}
            </div>

            {/* Secret Security Phrase */}
            <div>
              <div className="flex justify-between items-center mb-1.5">
                <label className="block text-[11px] font-bold text-slate-400 uppercase tracking-wider">
                  Secret Security Key
                </label>
                <button
                  type="button"
                  className="text-[10px] font-semibold text-purple-400 hover:underline"
                  onClick={() => alert('Please contact system administrator to initiate security keys reset.')}
                >
                  Forgot Key?
                </button>
              </div>
              <div className="relative">
                <span className="absolute inset-y-0 left-0 pl-3 flex items-center text-slate-500">
                  <Lock className="w-4 h-4" />
                </span>
                <input
                  type={showPassword ? 'text' : 'password'}
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className={`w-full bg-slate-950 border text-sm text-slate-200 rounded-xl pl-10 pr-10 py-2.5 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500/20 transition-all font-mono ${
                    validationErrors.password ? 'border-red-500/50' : 'border-slate-850'
                  }`}
                  placeholder="••••••••"
                />
                <button
                  type="button"
                  onClick={() => setShowPassword(!showPassword)}
                  className="absolute inset-y-0 right-0 pr-3 flex items-center text-slate-500 hover:text-slate-300"
                >
                  {showPassword ? <EyeOff className="w-4 h-4" /> : <Eye className="w-4 h-4" />}
                </button>
              </div>
              {validationErrors.password && (
                <p className="text-[10px] text-red-400 mt-1 flex items-center gap-1">
                  <AlertCircle className="w-3 h-3" /> {validationErrors.password}
                </p>
              )}
            </div>

            {/* Remember Me Flag */}
            <div className="flex items-center">
              <label className="relative flex items-center cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={rememberMe}
                  onChange={(e) => setRememberMe(e.target.checked)}
                  className="sr-only peer"
                />
                <div className="w-8 h-4.5 bg-slate-950 border border-slate-800 rounded-full peer peer-checked:after:translate-x-full after:content-[''] after:absolute after:top-[4px] after:left-[4px] after:bg-slate-500 peer-checked:after:bg-purple-400 after:rounded-full after:h-2.5 after:w-2.5 after:transition-all peer-checked:border-purple-500/30 peer-checked:bg-purple-500/10" />
                <span className="ml-2.5 text-xs text-slate-400 font-medium">Keep session pinned on this terminal</span>
              </label>
            </div>

            {/* Action Trigger Button */}
            <button
              type="submit"
              disabled={isLoading}
              className="w-full bg-purple-600 hover:bg-purple-500 text-white font-bold py-2.5 rounded-xl transition-all shadow-lg hover:shadow-purple-500/10 flex items-center justify-center gap-2 text-xs uppercase tracking-wider select-none active:scale-[0.98] disabled:opacity-50 disabled:pointer-events-none disabled:active:scale-100 mt-2"
            >
              {isLoading ? (
                <>
                  <div className="w-3.5 h-3.5 border-2 border-white border-t-transparent rounded-full animate-spin" />
                  <span>Verifying clearance logs...</span>
                </>
              ) : (
                <>
                  <span>Initialize Terminal Session</span>
                  <ChevronRight className="w-4 h-4" />
                </>
              )}
            </button>

          </form>

        </div>

        {/* Security Warning Footer banner */}
        <div className="p-4 bg-slate-950/60 border-t border-slate-850 flex items-center gap-3 text-[10px] text-slate-500">
          <BadgeCheck className="w-4 h-4 text-slate-600 shrink-0" />
          <span>Unauthorized access attempts are logged under Federal Law. Action requires explicit security tokens.</span>
        </div>

      </div>
    </div>
  );
}