import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { Plus, Search } from "lucide-react";
import { CrimeCard } from "../components/crime/CrimeCard";
import { CrimeFilterSidebar } from "../components/crime/CrimeFilterSidebar";
import { crimeService } from "../services/crimeService";
import type { Crime, CrimeFilters } from "../types/crime";
import { useAuth } from "../context/AuthContext";
export function CrimeListPage() { const { user } = useAuth(); const [crimes, setCrimes] = useState<Crime[]>([]); const [filters, setFilters] = useState<CrimeFilters>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); useEffect(() => { const load = async () => { setLoading(true); setError(""); try { setCrimes(await crimeService.list(filters)); } catch { setError("Unable to load crime reports."); } finally { setLoading(false); } }; void load(); }, [filters]); return <main className="page-shell"><div className="page-heading page-actions"><div><p className="eyebrow">Crime reporting</p><h1>{user?.role === "citizen" ? "My complaints" : "Crime reports"}</h1><p>Reports available under your assigned access level.</p></div>{user?.role === "citizen" && <Link className="primary-button" to="/crimes/report"><Plus size={17} /> Report crime</Link>}</div><div className="crime-list-layout"><CrimeFilterSidebar filters={filters} onChange={setFilters} onClear={() => setFilters({})} /><section><div className="search-bar"><Search size={18} /><input value={filters.query || ""} onChange={(event) => setFilters({ ...filters, query: event.target.value })} placeholder="Search title, description, or crime number" /></div>{loading ? <div className="content-loader">Loading reports…</div> : error ? <p className="form-error">{error}</p> : crimes.length ? <div className="card-grid">{crimes.map((crime) => <CrimeCard crime={crime} key={crime.id} />)}</div> : <div className="empty-state"><h2>No reports found</h2><p>Change your filters or submit a new complaint.</p></div>}</section></div></main>; }
